mobile_base_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'joint_left_wheel'
    right_wheel : 'joint_right_wheel'
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 10

    # Base frame_id
    base_frame_id: link_chassis

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # linear:
    #     x:
    #         has_velocity_limits    : true
    #         max_velocity           : 0.7  # m/s
    #         has_acceleration_limits: true
    #         max_acceleration       : 0.7  # m/s^2
    # angular:
    #     z:
    #         has_velocity_limits    : true
    #         max_velocity           : 2.7  # rad/s
    #         has_acceleration_limits: true
    #         max_acceleration       : 4.0  # rad/s^2
