gazebo_ros_control/pid_gains:
    allow_none: true
    # joint_left_wheel: {p: 2.5, i: 65.6, d: 0.0}
    # joint_right_wheel: {p: 2.5, i: 65.6, d: 0.0}
    # joint_left_wheel: {p: 0.1, i: 0.1, d: 0.0}
    # joint_right_wheel: {p: 0.1, i: 0.1, d: 0.0}
